const USER_DATA = 'show-donor';
const LOGIN ='login';
const CHANGEPASSWORD ='change-password';
const PROFILE ='userData';
const UPDATE_PROFILE ='update-user-data';
const DONORDATA='users';
const REGISTER = 'register';
const GOVERNORATE = 'governorate';
const CITY = 'city';